/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 16:47:53 BRST 2018
 */

package com.github.jimsp.gate.dto.response;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

import com.github.jimsp.gate.dto.request.GroupOperationRequestDto;

public class GroupOperationResponseDto_ESTest {

	@Test
	public void test0() throws Throwable {
		GroupOperationResponseDto groupOperationResponseDto0 = GroupOperationResponseDto
				.create((GroupOperationRequestDto) null);
		GroupOperationRequestDto groupOperationRequestDto0 = groupOperationResponseDto0.getGroupOperationRequestDto();
		assertNull(groupOperationRequestDto0);
	}

	@Test
	public void test1() throws Throwable {
		GroupOperationResponseDto groupOperationResponseDto0 = GroupOperationResponseDto
				.create((GroupOperationRequestDto) null);
		String string0 = groupOperationResponseDto0.toString();
		assertEquals("GroupOperationResponseDto [groupOperationRequestDto=null]", string0);
	}

	@Test
	public void test2() throws Throwable {
		GroupOperationRequestDto groupOperationRequestDto0 = new GroupOperationRequestDto("", "");
		GroupOperationResponseDto groupOperationResponseDto0 = GroupOperationResponseDto
				.create(groupOperationRequestDto0);
		GroupOperationRequestDto groupOperationRequestDto1 = groupOperationResponseDto0.getGroupOperationRequestDto();
		assertEquals("", groupOperationRequestDto1.getName());
	}

	@Test
	public void test3() throws Throwable {
		GroupOperationResponseDto groupOperationResponseDto0 = new GroupOperationResponseDto(
				(GroupOperationRequestDto) null);
		assertEquals(null, groupOperationResponseDto0.getGroupOperationRequestDto());
	}
}
