/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 16:48:47 BRST 2018
 */

package com.github.jimsp.gate.dto.response;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;

import org.junit.Test;

import com.github.jimsp.gate.dto.request.OperationRequestDto;
import com.github.jimsp.gate.dto.request.PermissionRequestDto;
import com.github.jimsp.gate.dto.request.ResourceRequestDto;

public class PermissionResponseDto_ESTest {

	@Test
	public void test0() throws Throwable {
		PermissionResponseDto permissionResponseDto0 = PermissionResponseDto.create((PermissionRequestDto) null);
		PermissionRequestDto permissionRequestDto0 = permissionResponseDto0.getPermissionRequestDto();
		assertNull(permissionRequestDto0);
	}

	@Test
	public void test1() throws Throwable {
		Boolean boolean0 = Boolean.valueOf("");
		ResourceRequestDto resourceRequestDto0 = new ResourceRequestDto("", boolean0, boolean0);
		PermissionRequestDto permissionRequestDto0 = new PermissionRequestDto("", "", boolean0,
				(OperationRequestDto) null, resourceRequestDto0);
		PermissionResponseDto permissionResponseDto0 = new PermissionResponseDto(permissionRequestDto0);
		PermissionRequestDto permissionRequestDto1 = permissionResponseDto0.getPermissionRequestDto();
		assertSame(permissionRequestDto1, permissionRequestDto0);
	}
}
