/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 16:49:14 BRST 2018
 */

package com.github.jimsp.gate.dto.response;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

import com.github.jimsp.gate.dto.request.ResourceRequestDto;

public class ResourceResponseDto_ESTest {

	@Test
	public void test0() throws Throwable {
		ResourceResponseDto resourceResponseDto0 = ResourceResponseDto.create((ResourceRequestDto) null);
		ResourceRequestDto resourceRequestDto0 = resourceResponseDto0.getResourceRequestDto();
		assertNull(resourceRequestDto0);
	}

	@Test
	public void test1() throws Throwable {
		ResourceRequestDto resourceRequestDto0 = ResourceRequestDto.create("", (Boolean) null, (Boolean) null);
		ResourceResponseDto resourceResponseDto0 = new ResourceResponseDto(resourceRequestDto0);
		assertEquals(resourceRequestDto0, resourceResponseDto0.getResourceRequestDto());
	}

	@Test
	public void test2() throws Throwable {
		Boolean boolean0 = new Boolean("");
		ResourceRequestDto resourceRequestDto0 = ResourceRequestDto.create("", boolean0, boolean0);
		ResourceResponseDto resourceResponseDto0 = ResourceResponseDto.create(resourceRequestDto0);
		ResourceRequestDto resourceRequestDto1 = resourceResponseDto0.getResourceRequestDto();
		assertEquals("", resourceRequestDto1.getName());
	}
}
