/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 16:49:43 BRST 2018
 */

package com.github.jimsp.gate.dto.response;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;

import java.util.LinkedList;

import org.junit.Test;

import com.github.jimsp.gate.dto.request.PermissionRequestDto;
import com.github.jimsp.gate.dto.request.RoleRequestDto;

public class RoleResponseDto_ESTest {

	@Test
	public void test0() throws Throwable {
		RoleResponseDto roleResponseDto0 = new RoleResponseDto((RoleRequestDto) null);
		RoleRequestDto roleRequestDto0 = roleResponseDto0.getRoleRequestDto();
		assertNull(roleRequestDto0);
	}

	@Test
	public void test1() throws Throwable {
		Boolean boolean0 = Boolean.valueOf("");
		LinkedList<PermissionRequestDto> linkedList0 = new LinkedList<PermissionRequestDto>();
		LinkedList<RoleRequestDto> linkedList1 = new LinkedList<RoleRequestDto>();
		RoleRequestDto roleRequestDto0 = new RoleRequestDto("", "", boolean0, boolean0, linkedList0, linkedList1);
		RoleResponseDto roleResponseDto0 = RoleResponseDto.create(roleRequestDto0);
		RoleRequestDto roleRequestDto1 = roleResponseDto0.getRoleRequestDto();
		assertFalse(roleRequestDto1.getPermanent());
	}
}
