/*
 * This file was automatically generated by EvoSuite
 * Tue Feb 13 16:50:12 BRST 2018
 */

package com.github.jimsp.gate.dto.response;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.Date;

import org.junit.Test;

import com.github.jimsp.gate.dto.request.UserOperationRequestDto;

public class UserOperationResponseDto_ESTest {

	@Test
	public void test0() throws Throwable {
		Date date0 = new Date(0L);
		UserOperationRequestDto userOperationRequestDto0 = UserOperationRequestDto.create((String) null, "", date0);
		UserOperationResponseDto userOperationResponseDto0 = new UserOperationResponseDto(userOperationRequestDto0,
				(String) null);
		String string0 = userOperationResponseDto0.getToken();
		assertNull(string0);
	}

	@Test
	public void test1() throws Throwable {
		UserOperationResponseDto userOperationResponseDto0 = UserOperationResponseDto
				.create((UserOperationRequestDto) null, "t");
		String string0 = userOperationResponseDto0.getToken();
		assertEquals("t", string0);
	}

	@Test
	public void test2() throws Throwable {
		Date date0 = new Date(0L);
		UserOperationRequestDto userOperationRequestDto0 = new UserOperationRequestDto("", "", date0);
		UserOperationResponseDto userOperationResponseDto0 = new UserOperationResponseDto(userOperationRequestDto0, "");
		UserOperationRequestDto userOperationRequestDto1 = userOperationResponseDto0.getUserAuthenticationRequestDto();
		assertEquals("", userOperationRequestDto1.getUsername());
	}

	@Test
	public void test3() throws Throwable {
		UserOperationRequestDto userOperationRequestDto0 = new UserOperationRequestDto("", "", (Date) null);
		UserOperationResponseDto userOperationResponseDto0 = new UserOperationResponseDto(userOperationRequestDto0, "");
		String string0 = userOperationResponseDto0.getToken();
		assertEquals("", string0);
	}

	@Test
	public void test4() throws Throwable {
		UserOperationResponseDto userOperationResponseDto0 = UserOperationResponseDto
				.create((UserOperationRequestDto) null, "");
		UserOperationRequestDto userOperationRequestDto0 = userOperationResponseDto0.getUserAuthenticationRequestDto();
		assertNull(userOperationRequestDto0);
	}
}
